# Generated by Django 5.1.3 on 2026-04-25 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('role', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('required_skills', models.CharField(max_length=320)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract')], default='full-time', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('cover_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.jobpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=180)),
                ('recruiter_name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=140)),
                ('company_website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.recruiterprofile'),
        ),
        migrations.CreateModel(
            name='ProjectValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_validations', to='core.jobapplication')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_validations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_validations', to='core.project')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_validations', to='core.recruiterprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recruiter', 'candidate', 'project', 'application')},
            },
        ),
    ]
