# Generated by Django 5.1.3 on 2026-04-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobpost_jobapplication_recruiterprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='recruiter_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
